name       : kicad
version    : 4.0.6
release    : 6
source     :
    - https://launchpad.net/kicad/4.0/4.0.6/+download/kicad-4.0.6.tar.xz : e97cacc179839e65f2afa14d8830a3bed549aaa9ed234c988851971bf2a42298
license    : GPL-3.0
component  : office
summary    : KiCad is an open source software suite for Electronic Design Automation
    (EDA).
description: |
    KiCad is an open source software suite for Electronic Design Automation (EDA).
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gl)
    - pkgconfig(glew)
    - pkgconfig(libcurl)
    - freeglut-devel
    - libboost-devel
    - wxwidgets-devel
setup      : |
    %patch -p1 < $pkgfiles/boost-1.61.patch
    %cmake -DCMAKE_INSTALL_PREFIX=/usr \
           -DCMAKE_BUILD_TYPE=Release \
           -DKICAD_BUILD_DYNAMIC=1 \
           -DKICAD_SKIP_BOOST=1 .
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/mimelnk
