name       : kicad
version    : 7.0.6
release    : 26
source     :
    - https://github.com/KiCad/kicad-source-mirror/archive/refs/tags/7.0.6.tar.gz : d01f67dc8d506b6e3b6dd3c8c785c8d872d5b46aa1e069c02481167af158334f
homepage   : https://www.kicad.org/
license    : GPL-3.0-or-later
component  : office.scientific
summary    : KiCad is an open source software suite for Electronic Design Automation
description: |
    KiCad is an open source software suite for Electronic Design Automation (EDA).
libsplit   : no
builddeps  :
    - pkgconfig(dri)
    - pkgconfig(cairo)
    - pkgconfig(glm)
    - pkgconfig(glew)
    - pkgconfig(glut)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcurl)
    - pkgconfig(odbc)
    - pkgconfig(python3)
    - pkgconfig(x11)
    - libboost-devel
    - ngspice-devel
    - opencascade-devel
    - swig
    - wxPython
    - wxwidgets-devel
rundeps    :
    - kicad-footprints
    - kicad-packages3d
    - kicad-symbols
    - kicad-templates
    - ngspice-devel
clang      : yes
setup      : |
    %cmake -B build \
        -DKICAD_USE_EGL=TRUE \
        -DKICAD_SCRIPTING_WXPYTHON=OFF \
        -DKICAD_USE_OCE=OFF \
        -DKICAD_USE_OCC=ON \
        -DKICAD_I18N_UNIX_STRICT_PATH=ON
build      : |
    %make -C build
install    : |
    %make_install -C build
    rm -rf $installdir/usr/share/mimelnk
