name       : kicad
version    : 4.0.2
release    : 2
source     :
    - https://launchpad.net/kicad/4.0/4.0.2/+download/kicad-4.0.2.tar.xz : 2eae6986843a29862ab399a30b50454582d22f58ed3f53eb50d0c85e5d488eb9
license    : GPL-3.0
component  : office
summary    : KiCad is an open source software suite for Electronic Design Automation (EDA).
description: |
    KiCad is an open source software suite for Electronic Design Automation (EDA).
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gl)
    - pkgconfig(glew)
    - pkgconfig(libcurl)
    - freeglut-devel
    - libboost-devel
    - wxwidgets-devel
setup      : |
    %cmake -DCMAKE_INSTALL_PREFIX=/usr \
           -DCMAKE_BUILD_TYPE=Release \
           -DKICAD_BUILD_DYNAMIC=1 \
           -DKICAD_SKIP_BOOST=1 .
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/mimelnk
