name       : kicad
version    : 5.1.6
release    : 20
source     :
    - https://github.com/KiCad/kicad-source-mirror/archive/5.1.6.tar.gz : caf54b256f17171d4be57c1905ab6a0d3bce1de7226e1f9b152c6501507cad52
license    : GPL-3.0-or-later
component  : office.scientific
summary    : KiCad is an open source software suite for Electronic Design Automation
description: |
    KiCad is an open source software suite for Electronic Design Automation (EDA).
libsplit   : no
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gl)
    - pkgconfig(glew)
    - pkgconfig(libcurl)
    - pkgconfig(x11)
    - freeglut-devel
    - glm
    - libboost-devel
    - ngspice-devel
    - opencascade-ce-devel
    - swig
    - wxwidgets-devel
rundeps    :
    - kicad-footprints
    - kicad-i18n
    - kicad-packages3d
    - kicad-symbols
    - kicad-templates
    - ngspice-devel
clang      : yes
setup      : |
    %cmake -DKICAD_SCRIPTING_WXPYTHON=OFF .
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/mimelnk
