name       : kicad
version    : 5.1.2
release    : 19
source     :
    - https://github.com/KiCad/kicad-source-mirror/archive/5.1.2.tar.gz : b181e81fe25929dd86900790e07067e28c62eaaf954d3a4a7ac4f18ed4745e42
license    : GPL-3.0-or-later
component  : office
summary    : KiCad is an open source software suite for Electronic Design Automation
description: |
    KiCad is an open source software suite for Electronic Design Automation (EDA).
libsplit   : no
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gl)
    - pkgconfig(glew)
    - pkgconfig(libcurl)
    - freeglut-devel
    - glm
    - libboost-devel
    - ngspice-devel
    - opencascade-ce-devel
    - swig
    - wxwidgets-devel
rundeps    :
    - kicad-footprints
    - kicad-i18n
    - kicad-packages3d
    - kicad-symbols
    - kicad-templates
    - ngspice-devel
clang      : yes
setup      : |
    %cmake -DKICAD_SCRIPTING_WXPYTHON=OFF .
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/mimelnk
