name       : kicad
version    : 4.0.7
release    : 8
source     :
    - https://launchpad.net/kicad/4.0/4.0.7/+download/kicad-4.0.7.tar.xz : 09074c77c6097d0f2ae49711c6d6f6c4490f0c068bba69b17f5f07319255fdc1
license    : GPL-3.0
component  : office
summary    : KiCad is an open source software suite for Electronic Design Automation
    (EDA).
description: |
    KiCad is an open source software suite for Electronic Design Automation (EDA).
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gl)
    - pkgconfig(glew)
    - pkgconfig(libcurl)
    - freeglut-devel
    - libboost-devel
    - wxwidgets-devel
rundeps    :
    - kicad-library
setup      : |
    %patch -p1 < $pkgfiles/boost-1.61.patch
    %cmake -DCMAKE_INSTALL_PREFIX=/usr \
           -DCMAKE_BUILD_TYPE=Release \
           -DKICAD_BUILD_DYNAMIC=1 \
           -DKICAD_SKIP_BOOST=1 .
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/mimelnk
