name       : kicad
version    : 5.0.0
release    : 15
source     :
    - https://launchpad.net/kicad/5.0/5.0.0/+download/kicad-5.0.0.tar.xz : 377582e4287146186593d42a5a7fe761590a79404982524ce445b4edbf96d89e
license    : GPL-3.0-or-later
component  : office
summary    : KiCad is an open source software suite for Electronic Design Automation
description: |
    KiCad is an open source software suite for Electronic Design Automation (EDA).
libsplit   : no
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gl)
    - pkgconfig(glew)
    - pkgconfig(libcurl)
    - freeglut-devel
    - glm
    - libboost-devel
    - ngspice-devel
    - opencascade-ce-devel
    - swig
    - wxPython-devel
    - wxwidgets-devel
rundeps    :
    - kicad-footprints
    - kicad-i18n
    - kicad-packages3d
    - kicad-symbols
    - kicad-templates
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/mimelnk
